# Generated by Django 5.2 on 2025-04-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charvarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
