# Generated by Django 5.2 on 2025-04-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_charvarity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='charvarity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
