# Generated by Django 5.2 on 2025-04-18 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_category_courseenrollment_coursereview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prerequisites',
            name='advanced_course',
        ),
        migrations.RemoveField(
            model_name='prerequisites',
            name='basic_course',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Prerequisites',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
