# Generated by Django 5.2 on 2025-04-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_remove_prerequisites_advanced_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='charvarity',
            name='duration',
            field=models.CharField(default='10 hours', max_length=20),
        ),
        migrations.AddField(
            model_name='charvarity',
            name='instructor',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='charvarity',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='charvarity',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='charvarity',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
        ),
        migrations.AddField(
            model_name='charvarity',
            name='students_enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='charvarity',
            name='type',
            field=models.CharField(choices=[('py', 'Python'), ('java', 'Java'), ('cpp', 'C++'), ('js', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('sql', 'SQL'), ('react', 'React'), ('django', 'Django'), ('node', 'Node.js'), ('ml', 'Machine Learning'), ('ai', 'Artificial Intelligence')], max_length=10),
        ),
    ]
